# Generated by Django 3.2.6 on 2021-08-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(choices=[(0, 'Draft'), (1, 'Publish')], default=True),
        ),
    ]
