# Generated by Django 3.2.6 on 2021-09-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_keyword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keyword',
            new_name='KeywordModel',
        ),
    ]
