# Generated by Django 3.2.6 on 2021-09-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_keyword_keywordmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeywordModel',
        ),
    ]
